import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/providers";
import Background from "@/app/components/Background";
import Header from "@/app/components/Header";

const JosefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${JosefinSans.className} antialiased min-h-screen flex justify-center mt-12 dark:bg-bodyBackground`}
      >
        <Providers>
          <Background />
          <main className="w-full min-w-[22rem] max-w-[50rem] flex flex-col items-center gap-12 p-8">
            <Header />
            {children}
            <footer className="static bottom-20 mt-24">
              <p>Drag and drop to reorder list</p>
            </footer>
          </main>
        </Providers>
      </body>
    </html>
  );
}
