import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { Providers, AuthProvider } from "@/app/providers";
import Background from "@/app/components/Background";
import Header from "@/app/components/Header";
import StyledComponentsRegistry from "./registry";
import Auth from "@/app/components/Auth";
import { TodosProvider } from "@/app/context/todos";

const JosefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="antialiased">
      <body
        className={`${JosefinSans.className} antialiased min-h-screen flex justify-center mt-12 dark:bg-bodyBackground`}
      >
        <StyledComponentsRegistry>
          <Providers>
            <AuthProvider>
              <Background />
              <Auth />
              <main className="w-full min-w-[22rem] max-w-[50rem] mt-4 flex flex-col items-center gap-12 p-8">
                <Header />
                <TodosProvider>{children}</TodosProvider>
                <footer className="static bottom-20 mt-24">
                  <p>Drag and drop to reorder list</p>
                </footer>
              </main>
            </AuthProvider>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
